from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class ResearchPlan(BaseModel):
    """The plan generated by the planner node.

    Maps resolved tickers to their sectors so that sector collection
    and sector synthesis nodes can run concurrently.
    """

    tickers: list[str] = Field(description="Canonical tickers to analyze")
    sectors: list[str] = Field(description="Unique sectors associated with the tickers")
    ticker_to_sector: dict[str, str] = Field(
        description="Map of canonical ticker to its sector name"
    )


class MacroSynthesis(BaseModel):
    """Output of the market-wide macro synthesis node."""

    outlook: Literal["bullish", "neutral", "bearish"] = Field(
        description="Market-wide short-term outlook"
    )
    key_drivers: list[str] = Field(
        description="Top 3-5 macro drivers with [id] citations"
    )
    analysis_markdown: str = Field(
        description="Detailed macro narrative (Markdown format) with [id] citations"
    )


class SectorSynthesis(BaseModel):
    """Output of the sector-level synthesis node."""

    sector_name: str
    outlook: Literal["bullish", "neutral", "bearish"] = Field(
        description="Sector outlook"
    )
    key_drivers: list[str] = Field(
        description="Top 3-5 sector drivers with [id] citations"
    )
    analysis_markdown: str = Field(
        description="Detailed sector analysis (Markdown format) with [id] citations"
    )


class TickerSynthesis(BaseModel):
    """Output of the ticker-level synthesis node."""

    canonical_ticker: str
    recommendation: Literal[
        "buy", "add", "hold", "reduce", "watch", "no_action", "insufficient_data"
    ]
    confidence_score: int = Field(
        ge=0, le=100, description="Confidence in the recommendation (0-100)"
    )
    target_price: float | None = Field(
        default=None, description="12-month target price (INR), or null if insufficient data"
    )
    rationale: list[str] = Field(
        description="Key points of investment rationale with [id] citations"
    )
    risk_factors: list[str] = Field(
        description="Key risk factors with [id] citations"
    )
    bear_case: str = Field(
        description="Detailed downside scenario analysis with [id] citations"
    )
    kill_the_company: str = Field(
        description="Structural/catastrophic risk that could ruin the company (non-generic)"
    )
    analysis_markdown: str = Field(
        description="Detailed company-specific analysis (Markdown format) with [id] citations"
    )


class PortfolioSynthesis(BaseModel):
    """Output of the portfolio aggregation/synthesis node."""

    allocation_adjustments: list[str] = Field(
        description="Suggested portfolio allocation adjustments with rationales referencing [id]"
    )
    top_picks: list[str] = Field(
        description="Top high-conviction tickers from the watchlist"
    )
    risk_aggregates: str = Field(
        description="Markdown overview of portfolio risk concentration"
    )
    analysis_markdown: str = Field(
        description="Detailed portfolio-wide synthesis narrative with [id] citations"
    )
